### ISSUE TITLE
Django 4 support 

### ISSUE THREAD

**Issue by landoephan** [vbabiy/djangorestframework-camel-case#103]
force_text and pytz are not part of django anymore. Is there a release that is compatible with django 4?

**Comment by jairhenrique** [comment]
This commit c988ced294cf0895b905dfdae3aebdd91e3bfc41 fixes this issue.
@vbabiy can you bump a new lib version?

**Comment by landoephan** [comment]
is the lib version updated?

**Comment by vbabiy** [comment]
@landoephan and @jairhenrique will be released later today

**Comment by vbabiy** [comment]
Released!
