### ISSUE TITLE
Does not work with DRF 3.0

### ISSUE THREAD

**Issue by lylepratt** [vbabiy/djangorestframework-camel-case#11]
This does not appear to work with DRF 3.0 on POST or PUTs. It renders fine, but does not work when camel cased fields are passed to create or update items.

**Comment by jacobg** [comment]
Works fine for me.

**Comment by dbrgn** [comment]
Are you sending the requests as `multipart/form-data`? Might be related to #1346.

In my case, to get the test suite to run, `TEST_REQUEST_DEFAULT_FORMAT='json'` helped.
