### ISSUE TITLE
camelize regex should be pre-compiled

### ISSUE THREAD

**Issue by rchrd2** [vbabiy/djangorestframework-camel-case#16]
In profiling a recent application, I noticed that `camelize` added some load time. 

Some other regexes are precomiled, so it seems like an oversight that the regex in `camelize` is not also compiled. 

eg:

```
camelize_re = re.compile(r"[a-z]_[a-z]")
...
new_key = camelize_re.sub(underscoreToCamel, key)
```

https://github.com/vbabiy/djangorestframework-camel-case/blob/master/djangorestframework_camel_case/util.py

**Comment by rchrd2** [comment]
Another optimization:

Skip regex altogether if no "_" is in the key. eg.
```
if "_" in key:
     # do regex
```

**Comment by vbabiy** [comment]
Thanks @rchrd2
