### ISSUE TITLE
Can't assign items to tuple

### ISSUE THREAD

**Issue by merwok** [vbabiy/djangorestframework-camel-case#24]
Hello and thanks for making this package!  I have a field that exists as a tuple before being serialized to a list.  With drf-camel-case, there is an exception coming from the camelize function:

    if isinstance(data, (list, tuple)):
        for i in range(len(data)):
            data[i] = camelize(data[i])

Tuples don’t support item assignment.

Suggested fix:

    if isinstance(data, tuple):
        data = list(data)
    if isinstance(data, list):
        for i in range(len(data)):
            data[i] = camelize(data[i])

**Comment by merwok** [comment]
Pull request #19 solves this!

**Comment by vbabiy** [comment]
Fixed on master

@merwok thanks for the report
