### ISSUE TITLE
Need escape hatch

### ISSUE THREAD

**Issue by merwok** [vbabiy/djangorestframework-camel-case#25]
It would be useful to have a way to let an object be rendered without transformation.

Suggestion: add a marker class used like `return Response({'valid_values': nocamel(some_choices)})` and change the camelize function to not change these objects.  The result here would be `{"validValues": [["thing_one", "Thing one"], ["thing_two", "Thing two"]]}`.

**Comment by timworx** [comment]
You can specify the parser/renderer [per view as well](http://www.django-rest-framework.org/api-guide/renderers/). You can use that to override camel case.

**Comment by merwok** [comment]
In my example, the desired output had camel case for some keys and no transformation for others (I forgot what my original use case was, maybe geojson).  But you’re right that for such a specialized need I can implement my own renderer subclass and nocamel marker!
