### ISSUE TITLE
CamelCaseJSONRenderer alter response.data

### ISSUE THREAD

**Issue by magul** [vbabiy/djangorestframework-camel-case#26]
As it says in Django REST Framework [documentation](http://www.django-rest-framework.org/api-guide/responses/#data)

> .data
> The unrendered content of a Request object.

Unfortunatelly it occurs that `CamelCaseJSONRenderer` is changing `response.data` from

```
{ 'abc_def': True }
```
into
```
{ 'abcDef': True }
```

For minimal example see: https://github.com/magul/drf-cc-26 (there are 4 tests and 1 is failing because of the issue).

**Comment by sadan** [comment]
Any idea if this package works with latest DRF?

**Comment by magul** [comment]
@sadan as You can see in https://github.com/magul/drf-cc-26 I'm using it with
```
djangorestframework==3.6.2
```

**Comment by vstoykov** [comment]
Probably the issue is here https://github.com/vbabiy/djangorestframework-camel-case/blob/master/djangorestframework_camel_case/util.py#L21 because it will replace list items in place instead of creating new one as it do with `dict` objects.
Can you prepare a PR with a fix?

**Comment by vbabiy** [comment]
Thanks @magul for the report should be fixed on master
