### ISSUE TITLE
Renderer doesn't work with generators

### ISSUE THREAD

**Issue by fadawar** [vbabiy/djangorestframework-camel-case#33]
Hello,

first thank you for this module. :) Second, I found out it has problem if data in renderer are in form of a generator. Problem is in function `camelize`. Instead of checking if instance is list or tuple it should check if instance is iterable. Could you please fix it?

**Comment by vbabiy** [comment]
Merged, will release a package later today

**Comment by fadawar** [comment]
@vbabiy what happened? When will you release new version? Last stable version was in 2014.
