### ISSUE TITLE
tag new version

### ISSUE THREAD

**Issue by javialon26** [vbabiy/djangorestframework-camel-case#39]
can you generate a new version with Underscoreize feature? because the version installed by pip does not have this feature.

thank you!

**Comment by dgilge** [comment]
@vbabiy Any chance to release a new version? There are several users (including me) interested in the new features included in the master branch (see also #42).

**Comment by vbabiy** [comment]
https://pypi.org/project/djangorestframework-camel-case/1.0.0/
