### ISSUE TITLE
Doesn't camelize keys with numbers correctly

### ISSUE THREAD

**Issue by jdesrosiers** [vbabiy/djangorestframework-camel-case#42]
The key `address_line_1` renders as `AddressLine_1`. I expect it to be `AddressLine1`. Is there a reason for this, or can we fix it?

**Comment by jdesrosiers** [comment]
Actually, it looks like this was fixed back in November, but the fix hasn't been released to PyPi yet.

**Comment by jacobg** [comment]
+1 please publish to pypi

**Comment by fadawar** [comment]
I forked the repo and published new version on pypi
https://github.com/fadawar/djangorestframework-camel-case2

**Comment by vbabiy** [comment]
https://pypi.org/project/djangorestframework-camel-case/1.0.0/
