### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by python273** [vbabiy/djangorestframework-camel-case#51]
Please start making Change Log / using GitHub Releases, so it's possible to know what was changed (like https://github.com/vbabiy/djangorestframework-camel-case/issues/50)

**Comment by webyneter** [comment]
Releasing the latest master would also help a lot.

**Comment by vbabiy** [comment]
I have finally done it, 1.10 is out :fireworks: 

https://pypi.org/project/djangorestframework-camel-case/1.1.0/
