### ISSUE TITLE
Could not import 'rest_framework.renderers.UnicodeJSONRenderer'

### ISSUE THREAD

**Issue by luktar** [vbabiy/djangorestframework-camel-case#55]
I configured my django according to guide. The error occurs:

`ImportError: Could not import 'rest_framework.renderers.UnicodeJSONRenderer' for API setting 'RENDERER_CLASS'. AttributeError: module 'rest_framework.renderers' has no attribute 'UnicodeJSONRenderer'.`

Changing `UnicodeJSONRenderer` to `JSONRenderer` another error occurs:

`ImportError: Could not import 'djangorestframework_camel_case.parser.CamelCaseFormParser' for API setting 'DEFAULT_PARSER_CLASSES'. ModuleNotFoundError: No module named 'six'.`

**Comment by luktar** [comment]
`pip install six`

solved the problem

**Comment by belidzs** [comment]
six should be listed as a requirement in requirements.txt and setup.py as well

**Comment by vbabiy** [comment]
@belidzs @luktar this should be fixed in the latest release. Let me know if its not.
