### ISSUE TITLE
Initial problem

### ISSUE THREAD

**Issue by BreezeFreak** [vbabiy/djangorestframework-camel-case#56]
I having a problem when I get JSON data like:  
`>>> underscoreize({'HelloWord': 'HelloWorld'})`
`{'_hello_word': 'HelloWorld'}`  
---
Am i using it a wrong way?  
I got data from an API and this problem confused me.  
It seems no other issue refer to this case.  
Sorry about my bad English, and thanks for your work.

**Comment by Reyvel** [comment]
HelloWord isn't camelCase, it should be helloWorld
