### ISSUE TITLE
underscore_to_camel is not working with str

### ISSUE THREAD

**Issue by gumusoyku** [vbabiy/djangorestframework-camel-case#66]
I am using the library already so I would like to use the `underscore_to_camel` too.
but its not working with strings. 
Getting `*** AttributeError: 'str' object has no attribute 'group'` error

**Comment by vbabiy** [comment]
@gumusoyku can you include an example of how you're using it?

**Comment by gumusoyku** [comment]
@vbabiy  Hey, sorry, apparently this was on me. 
I am closing this issue since there is no problem. 😅
