### ISSUE TITLE
Version 1.0.3 in PyPI differs from version 1.0.3 on GitHub

### ISSUE THREAD

**Issue by robrichter** [vbabiy/djangorestframework-camel-case#67]
When you install version 1.0.3 from PyPI by pip install djangorestframework-camel-case you get completely different code than on GitHub. 

Few examples of differencies:
render module is missing class CamelCaseBrowsableAPIRenderer
parser module contains: from rest_framework.parsers import **six**, FormParser

**Comment by Alan-Solitar** [comment]
Seeing the same issue here.

**Comment by alexandremjacques** [comment]
Same here.

**Comment by HymanZHAN** [comment]
Same here. Not able to import renderers as a result.

**Comment by Racum** [comment]
Bump the version, publish on PyPI!

**Comment by jastee07** [comment]
Same issue. Is there a working version I can use until this one is updated?

**Comment by Alan-Solitar** [comment]
@robrichter @Racum @jastee07 @HymanZHAN @alexandremjacques

Seems like the master branch is indeed working fine even though the pypi version doesn't work.
 
What I did was instead just install the package directly from github using pipenv.  This can also be done with pip.

Basically I just ran the following command:

pipenv install git+https://github.com/vbabiy/djangorestframework-camel-case.git@master#egg=djangorestframework-camel-case


Not that it adds any information to what I said above or anything, but I wrote an article about it on my blog if anyone wants to check it out.
https://remotedevdaily.com/how-to-install-packages-from-github-with-pip-and-pipenv/

**Comment by nicolas-b12** [comment]
As you can see here, https://github.com/vbabiy/djangorestframework-camel-case/pull/65#issuecomment-516834922 @vbabiy said that he will review some other PRs before pushing a new version of PyPI. I'm sure it will be soon 😉

**Comment by michaelmarziani** [comment]
I just did a fresh install, latest DRF, latest DRF-camel-case from pypi and I'm having this issue:

`ImportError: cannot import name 'six' from 'rest_framework.parsers'`

I think it's important for plugins like this to work with the latest release version of the software they support. New users of DRF-camel-case for the past month have been getting this error and reasonably concluding that this isn't a supported project. I think that's bad for the project and for our community here.

**Comment by jastee07** [comment]
> I just did a fresh install, latest DRF, latest DRF-camel-case from pypi and I'm having this issue:
> 
> `ImportError: cannot import name 'six' from 'rest_framework.parsers'`
> 
> I think it's important for plugins like this to work with the latest release version of the software they support. New users of DRF-camel-case for the past month have been getting this error and reasonably concluding that this isn't a supported project. I think that's bad for the project and for our community here.

There is a second version someone made until this one is supported again: https://pypi.org/project/django-rest-framework-camel-case/

**Comment by YPCrumble** [comment]
@vbabiy in case you're looking for maintainers I would be happy to help. Also could be a good project to integrate with [jazzband](https://github.com/jazzband).

**Comment by canassa** [comment]
Hello everyone,

I use this dependency on several of my projects, therefore I decided to fork it push it PyPI:

https://github.com/canassa/djangorestframework-camel-case

You can install it with:

```
pip install djangorestframework-camel-case-2
```

It's a drop-in replacement. Feel free to use it!

**Comment by JonasKs** [comment]
> I use this dependency on several of my projects, therefore I decided to fork it push it PyPI:

I think a better solution would be to do a pip install with a commit, rather releasing a new package to PyPi. 
```
pip install git+https://github.com/vbabiy/djangorestframework-camel-case.git@39ae6bbde19d3fadc5b60505395c51f44b22a069  
``` 

Also, I get that you've put your information in the `setup.py` with your approach, but changing the [init](https://github.com/canassa/djangorestframework-camel-case/blob/master/djangorestframework_camel_case/__init__.py) to you does not make sense to me.

**Comment by canassa** [comment]
@JonasKs I was doing git+https install, but the problem is that it's a slower than a regular install from PyPI and I don't think it's cacheable by pip. I am also planning on adding extra features to it and merge some of the issues that are already open in here, so that's why I pushed it PyPI

Good point on the init, I am not very sure on how to proceed with that on forks. I don't want to give the impression that I am trying to steal anyone work 😉 but on the other hand I want to make sure that people get in contact with me and not vbabiy regarding issues and/or question about my fork.

**Comment by michaelmarziani** [comment]
If @canassa is willing to start maintaining a branch of this I'd use it. If at a later date @vbabiy is available again, they can work out merging back, sharing maintenance, whatever.

**Comment by vbabiy** [comment]
I have finally done it, 1.10 is out :fireworks: 

https://pypi.org/project/djangorestframework-camel-case/1.1.0/
