### ISSUE TITLE
Bad underscorization; util.camel_to_underscore('anotherKey1') returns 'another_key1'

### ISSUE THREAD

**Issue by akiyoko** [vbabiy/djangorestframework-camel-case#73]
I found weird underscorization. 

```
>>> from djangorestframework_camel_case.util import camel_to_underscore
>>> camel_to_underscore('anotherKey10')
'another_key_10'
```

That's OK :)

```
>>> camel_to_underscore('anotherKey1')
'another_key1'
```

That's weird. I hope that it should return 'another_key_1'.

My requirements are as follows:

```
Django==2.2.6
djangorestframework==3.10.3
djangorestframework-camel-case==1.1.2
```

**Comment by Kyle-Steven-Lewis** [comment]
I noticed this recently as well.  Setting your djangorestframework-camel-case version back to 1.1.1 seems to fix the issue.

**Comment by Kyle-Steven-Lewis** [comment]
Further note, it seems like `someThing1` becomes `some_thing1` whereas `some1Thing` becomes `some_1_thing`.  So it's only an issue if it ends with a number.

**Comment by akiyoko** [comment]
I found another case:

```
>>> from djangorestframework_camel_case.util import camel_to_underscore
>>> camel_to_underscore('optionS1')
'option_s1'
```
