### ISSUE TITLE
Ignore fields does not work as expected

### ISSUE THREAD

**Issue by michaelsizonenko** [vbabiy/djangorestframework-camel-case#86]
settings.py 

    "JSON_UNDERSCOREIZE": {
        # ...
        "ignore_fields": ("order_update", ),
        # ...
    }

Still got output response:

{
    "orderUpdate": {
        "items": [
            {
                "parent": null,
                "type": "tax",
                "description": "Sales taxes",
                "amount": 350,
                "currency": "usd"
            }
        ],
        "shipping_methods": [
            {
                "id": "free_shipping",
                "description": "Free 7-day shipping",
                "amount": 0,
                "currency": "usd",
                "delivery_estimate": {
                    "type": "exact",
                    "date": "2020-08-11"
                },
                "tax_items": []
            }
        ]
    }
}

**Comment by stevewilliamsuk** [comment]
Agree, can reproduce the issue at will. However, the proposed fix may alter the problem.

**Comment by djowett-ftw** [comment]
#89 does (roughly) what I wanted, however I have to admit that ignore_fields was coded with a different intention - see this comment:

https://github.com/vbabiy/djangorestframework-camel-case/pull/80#discussion_r440705463

**Comment by JupiterThreads** [comment]
Is this ignore keys pr going to get added soon? I would also benefit from this as I'm trying to turn a field 'id' to '_id'. Thanks!
